### ISSUE TITLE
`~i0 = i1` listed twice

### ISSUE THREAD

**Issue by LiamGoodacre** [plt-amy/cubical-1lab#18]
Was reading [this](https://cubical.1lab.dev/1Lab.Path.html) and noticed that `~i0 = i1` is listed twice [here](https://github.com/plt-amy/cubical-1lab/blob/30b6ac0c3f2d29c77dd0a00c01292602e9f77a99/src/1Lab/Path.lagda.md?plain=1#L78); I'm guessing one of them should change to `~i1 = i0`?

![Screenshot from 2021-12-28 17-27-13](https://user-images.githubusercontent.com/1189645/147591677-c825f4ea-59df-457a-8294-6b3333369d68.png)

**Comment by plt-amy** [comment]
Thanks for the catch!
