### ISSUE TITLE
So nice that you have a «Serif Font» check box!

### ISSUE THREAD

**Issue by kindaro** [plt-amy/cubical-1lab#24]
Usually I have to write a custom CSS that a browser extension lets me inject into web pages. So for example I have a CSS for GitHub that sets serif font as default. For once I am freed from this work!

**Comment by plt-amy** [comment]
I'm glad you like it but please use [Discussions](https://github.com/plt-amy/cubical-1lab/discussions) for things that aren't bug reports in the future. Thanks!
